# Generated by Django 5.0.3 on 2024-03-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='comision',
            new_name='comision_curso',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='nombre',
            new_name='nombre_curso',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='apellido',
            new_name='apellido_estudiante',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='email',
            new_name='email_estudiante',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='nombre',
            new_name='nombre_estudiante',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='apellido',
            new_name='apellido_profesor',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='email',
            new_name='email_profesor',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='especialidad',
            new_name='especialidad_profesor',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='nombre',
            new_name='nombre_profesor',
        ),
    ]
